[package]
name = "rustystatus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Clock
chrono = "0.4.38"

# Battery
battery = "0.7.8"
